### ISSUE TITLE
Problem with app.js

### ISSUE THREAD

**Issue by damian1304** [MartinsOnuoha/BlogCafe#38]
Hello
i have a question because we cloned the your github project blogcafe but after the install he have a problem with the app.js 
the images that have already been uploaded are not displayed
can you help us i attached a picture about the logg
dear team
![error](https://user-images.githubusercontent.com/24258490/145728655-fddbdb8f-11e7-4553-98f4-7a7883121bea.PNG)

**Comment by MartinsOnuoha** [comment]
Hello @damian1304, alright I'll have a look at this problem asap

**Comment by MartinsOnuoha** [comment]
Hello @damian1304 are you facing this issue on your local machine? or in production?

**Comment by damian1304** [comment]
We are using 2 Maschines 1 is a local server and after this we are tested it on a web server in a datacenter with plesk but both not working
