### ISSUE TITLE
Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException

### ISSUE THREAD

**Issue by trsihiadev** [MartinsOnuoha/BlogCafe#5]
Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException
The GET method is not supported for this route. Supported methods: POST.
http://localhost:8000/post/create_post

**Comment by trsihiadev** [comment]
:256
C:\xampp\htdocs\multipleimage\vendor\laravel\framework\src\Illuminate\Routing\RouteCollection.php:256

**Comment by trsihiadev** [comment]
by running tinker to insert post . It's okay, while runnign throught localhost:8000/post/create__post I got that error

**Comment by MartinsOnuoha** [comment]
Hello @trsihiadev, You shouldn't send a `GET` request to the `/post/create_post` endpoint, it only accepts `POST` request. When you send a get request, you get the `MethodNotAllowedHttpException` error.

I've made an update to resolve some other bugs. here https://github.com/MartinsOnuoha/BlogCafe/pull/8
