### ISSUE TITLE
TypeError: that.getAllPost in CreatePost.vue not a function

### ISSUE THREAD

**Issue by wbarnard81** [MartinsOnuoha/BlogCafe#9]
api.post('/post/create_post', formData, {headers: {'Content-Type': 'multipart/form-data'}})
        .then((res) => {
          this.title = this.body = '';
          this.status = true;
          this.showNotificaiton('Post Successfully Created');
          this.isCreatingPost = false;
          this.imageList = [];
          **that**.getAllPosts();
        });

**Comment by MartinsOnuoha** [comment]
@wbarnard81 this isn't a bug.
- Did you clone and test the app and faced any issue?
- If yes, can you show a detail of the issue you faced?

However, I have added a PR to include a comment on that line, so you understand why *that* is used in place of *this*.

**Comment by wbarnard81** [comment]
![error](https://user-images.githubusercontent.com/41894485/73715245-01054380-471c-11ea-8d40-371c937d7768.jpg)
Yes, I did clone it and this is the error I received. The first time, it updates the Posts, but it doesn't clear the image as well from the "create". The secodn time, it does not fetch the new posts and still does not clear the image from the "create".

**Comment by MartinsOnuoha** [comment]
@wbarnard81 would you like to create a PR to resolve this?
